CREATE TABLE video (
id INT AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
videoId VARCHAR(100) NOT NULL UNIQUE,
channelId VARCHAR(100) NOT NULL,
title VARCHAR(255) NOT NULL,
description VARCHAR(500) NOT NULL,
channelTitle VARCHAR(100) NOT NULL,
publishedAt DATETIME NOT NULL,
createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE test (
id INT AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
videoId VARCHAR(100) NOT NULL UNIQUE 
);