CREATE TABLE video (
id INT AUTO_INCREMENT NOT NULL UNIQUE PRIMARY KEY,
videoId VARCHAR(100) NOT NULL UNIQUE,
channelId VARCHAR(100) NOT NULL,
title TEXT NOT NULL,
description TEXT NOT NULL,
channelTitle TEXT NOT NULL,
publishedAt DATETIME NOT NULL,
thumbnail VARCHAR(200) NOT NULL,
createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
